/**
 * UI-side descriptors for the MCP tools this app exposes.
 *
 * The real runtime is generated by @lovable.dev/mcp-js from src/lib/mcp/.
 * This file only feeds the Settings > App host panel so users can see the
 * catalog without loading the server module in the browser.
 */

export interface McpToolDef {
  name: string;
  description: string;
  inputShape: string;
  category: "project" | "content" | "validation" | "assets" | "export";
}

export const MCP_TOOL_DEFS: readonly McpToolDef[] = [
  { name: "list_projects", description: "List the projects in your Mod Constructor account.", inputShape: "{}", category: "project" },
  { name: "get_project", description: "Get a project's metadata and resource counts.", inputShape: "{ project_id }", category: "project" },
  { name: "get_active_project", description: "Read the active project for the current connection.", inputShape: "{}", category: "project" },
  { name: "set_active_project", description: "Set the active project for the current connection.", inputShape: "{ project_id }", category: "project" },
  { name: "create_project", description: "Create a new project owned by your account.", inputShape: "{ name, description?, version? }", category: "project" },
  { name: "list_project_resources", description: "List resources in a project, optionally by kind.", inputShape: "{ project_id, kind? }", category: "project" },
  { name: "get_resource", description: "Get one resource by UUID.", inputShape: "{ project_id, resource_id }", category: "project" },
  { name: "create_trait", description: "Create a trait resource.", inputShape: "{ project_id, name, ... }", category: "content" },
  { name: "update_trait", description: "Update a trait resource.", inputShape: "{ project_id, resource_id, ... }", category: "content" },
  { name: "create_buff", description: "Create a buff resource.", inputShape: "{ project_id, name, ... }", category: "content" },
  { name: "update_buff", description: "Update a buff resource.", inputShape: "{ project_id, resource_id, ... }", category: "content" },
  { name: "create_interaction", description: "Create an interaction resource.", inputShape: "{ project_id, name, ... }", category: "content" },
  { name: "update_interaction", description: "Update an interaction resource.", inputShape: "{ project_id, resource_id, ... }", category: "content" },
  { name: "create_notification", description: "Create a notification resource.", inputShape: "{ project_id, name, title, body }", category: "content" },
  { name: "create_dialogue", description: "Create a dialogue resource.", inputShape: "{ project_id, name, ... }", category: "content" },
  { name: "create_career", description: "Create a career resource.", inputShape: "{ project_id, name, ... }", category: "content" },
  { name: "create_career_level", description: "Add a level to a career.", inputShape: "{ project_id, career_id, ... }", category: "content" },
  { name: "add_localized_string", description: "Add an STBL localized string.", inputShape: "{ project_id, key, value }", category: "content" },
  { name: "link_resources", description: "Link two resources together.", inputShape: "{ project_id, from_id, to_id, relation }", category: "content" },
  { name: "validate_resource", description: "Validate one resource.", inputShape: "{ project_id, resource_id }", category: "validation" },
  { name: "validate_project", description: "Validate an entire project.", inputShape: "{ project_id }", category: "validation" },
  { name: "create_build_manifest", description: "Build a manifest of everything to compile.", inputShape: "{ project_id }", category: "export" },
  { name: "request_project_build", description: "Request a package build (reports honestly if the compiler is unavailable).", inputShape: "{ project_id }", category: "export" },
  { name: "get_build_status", description: "Read the status of a build request.", inputShape: "{ project_id, build_id? }", category: "export" },
  { name: "undo_change_set", description: "Undo a recorded change set.", inputShape: "{ project_id, change_set_id }", category: "project" },
];
