/**
 * UI-side descriptors for the MCP tools this app exposes.
 *
 * The real runtime is generated by @lovable.dev/mcp-js from src/lib/mcp/.
 * This file only feeds the Settings > App host panel so users can see the
 * catalog without loading the server module in the browser.
 */

export interface McpToolDef {
  name: string;
  description: string;
  inputShape: string;
  category: "project" | "content" | "validation" | "assets" | "export";
}

export const MCP_TOOL_DEFS: readonly McpToolDef[] = [
  { name: "list_projects", description: "List every project inside a bundle.", inputShape: "{ bundle? }", category: "project" },
  { name: "get_project", description: "Get full project metadata and item counts.", inputShape: "{ bundle? }", category: "project" },
  { name: "list_careers", description: "List every career in a bundle.", inputShape: "{ bundle? }", category: "content" },
  { name: "list_traits", description: "List every trait in a bundle.", inputShape: "{ bundle? }", category: "content" },
  { name: "list_aspirations", description: "List every aspiration in a bundle.", inputShape: "{ bundle? }", category: "content" },
  { name: "list_notifications", description: "List every notification template in a bundle.", inputShape: "{ bundle? }", category: "content" },
  { name: "create_project", description: "Create a fresh Mod Constructor project bundle.", inputShape: "{ name, author?, description?, version? }", category: "project" },
  { name: "add_career", description: "Add a career with branches, levels, salary, schedule.", inputShape: "{ bundle?, name, internalId, branches[] }", category: "content" },
  { name: "add_trait", description: "Add a trait with buffs, age gates, category.", inputShape: "{ bundle?, name, internalId, category, buffs[] }", category: "content" },
  { name: "add_aspiration", description: "Add an aspiration with milestones.", inputShape: "{ bundle?, name, internalId, milestones[] }", category: "content" },
  { name: "add_notification", description: "Add an in-game notification template.", inputShape: "{ bundle?, name, title, body, visual }", category: "content" },
  { name: "set_project_status", description: "Set lifecycle status; auto-appends changelog on complete/tested/released.", inputShape: "{ bundle?, status, notes? }", category: "project" },
  { name: "bump_version", description: "Set a new version and reset status to in-progress.", inputShape: "{ bundle?, version }", category: "project" },
  { name: "export_bundle", description: "Return the bundle as downloadable .mcbundle.json.", inputShape: "{ bundle? }", category: "export" },
  { name: "import_bundle", description: "Parse and validate a .mcbundle.json string.", inputShape: "{ contents }", category: "export" },
  { name: "list_templates", description: "List built-in starter templates.", inputShape: "{ kind? }", category: "content" },
  { name: "use_template", description: "Scaffold a template's records into a bundle.", inputShape: "{ bundle?, templateId }", category: "content" },
  { name: "list_snippets", description: "List built-in XML/tuning snippets.", inputShape: "{}", category: "content" },
];
