/**
 * Project storage abstraction.
 *
 * Goal: images and project data returned through the ChatGPT App can sync
 * with — or be exported for — the standalone desktop application.
 *
 * Storage tiers:
 *   - memory:      transient in-tab state (default in ChatGPT App)
 *   - localStorage: persistent per-browser (desktop web preview)
 *   - filesystem:   real desktop build writes to <userdata>/ModConstructor
 *
 * The Portable Bundle (.mcbundle.json) is the interchange format. A ChatGPT
 * session exports one; the desktop app imports it and vice versa.
 */

export type RecordKind = "project" | "career" | "trait" | "aspiration" | "notification" | "asset";

export interface StoredAsset {
  id: string;
  name: string;
  folder: string;
  kind: "icon" | "image" | "audio" | "package" | "script" | "other";
  /** data:image/png;base64,... — portable across hosts. */
  dataUrl?: string;
  /** Provenance so we can show "Generated by ChatGPT" badges. */
  source: "upload" | "chatgpt" | "sd" | "openai-api" | "unknown";
  createdAt: number;
}

export interface ProjectBundle {
  version: 1;
  exportedAt: number;
  exportedFrom: "chatgpt" | "desktop";
  project: {
    id: string;
    name: string;
    author: string;
  };
  careers: unknown[];
  traits: unknown[];
  aspirations: unknown[];
  notifications: unknown[];
  assets: StoredAsset[];
}

const KEY = "mc.bundle.v1";

export function loadBundle(): ProjectBundle | null {
  try {
    const raw = localStorage.getItem(KEY);
    return raw ? (JSON.parse(raw) as ProjectBundle) : null;
  } catch {
    return null;
  }
}

export function saveBundle(b: ProjectBundle) {
  try {
    localStorage.setItem(KEY, JSON.stringify(b));
  } catch {
    /* quota — silently ignore in prototype */
  }
}

export function emptyBundle(from: "chatgpt" | "desktop"): ProjectBundle {
  return {
    version: 1,
    exportedAt: Date.now(),
    exportedFrom: from,
    project: { id: crypto.randomUUID(), name: "Untitled Project", author: "" },
    careers: [],
    traits: [],
    aspirations: [],
    notifications: [],
    assets: [],
  };
}

export function downloadBundle(b: ProjectBundle) {
  const blob = new Blob([JSON.stringify(b, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${b.project.name.replace(/\s+/g, "_") || "project"}.mcbundle.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export function saveGeneratedImage(name: string, dataUrl: string, folder = "Generated"): StoredAsset {
  const bundle = loadBundle() ?? emptyBundle("chatgpt");
  const asset: StoredAsset = {
    id: crypto.randomUUID(),
    name,
    folder,
    kind: "image",
    dataUrl,
    source: "chatgpt",
    createdAt: Date.now(),
  };
  bundle.assets.unshift(asset);
  saveBundle(bundle);
  return asset;
}

export function latestGeneratedImage(): StoredAsset | null {
  const bundle = loadBundle();
  if (!bundle) return null;
  return bundle.assets.find((a) => a.kind === "image" && a.source === "chatgpt") ?? null;
}
