/**
 * Built-in SimData templates.
 *
 * The Sims 4 refuses to load Trait / Buff / Career / Aspiration tuning without
 * a SimData companion of the same instance, and EA's exported column set is
 * patch-specific, so a hand-written schema is a guess. These are the real
 * SimData templates published with The Sims 4 Mod Constructor 5
 * (github.com/Zerbu/Mod-Constructor-5, SimData/*.data) — files the game
 * already loads. The exporter clones one, re-keys it onto the generated tuning
 * instance and rewrites the localisation keys in place, exactly as Mod
 * Constructor 5 does, so the structure stays byte-identical to a known-good
 * resource.
 */

import type { BuilderKind } from "./simdata";

/* eslint-disable */
const TEMPLATES_B64: Record<string, string> = {
  // Career.data (243 bytes)
  career:
    "REFUQQEBAAAYAAAAAQAAAFAAAAABAAAAAAAAAAAAAADHAAAApzcReDgAAAANAAAAGAAAAAwAAAABAAAAAAAAAAEAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAOtrmXPtm+Q2GAAAAAgAAAADAAAAPAAAANbw7HgIAAAAAAAAAAAAAIBIAAAA" +
    "H42DjRIAAAAQAAAAAAAAgCQAAAAKqry8AAAAAAgAAAAAAACAY2FyZWVyX2NhdGVnb3J5AHNob3dfaWRlYWxfbW9vZABzdGFy" +
    "dF90cmFjawBDYXJlZXIAQ29uc3RydWN0b3IA",
  // CareerLevel.data (1348 bytes)
  career_level:
    "REFUQQEBAAAYAAAABgAAAIABAAAFAAAAAAAAAAAAAAAYBQAApzcReGgBAAANAAAAOAAAAMwAAAABAAAAAAAAgMWdHIFkAQAA" +
    "DQAAAAgAAADwAAAAAQAAAAAAAIDFnRyBYAEAAA0AAAAQAAAA5AAAAAEAAAAAAACAxZ0cgVwBAAANAAAABwAAANgAAAABAAAA" +
    "AAAAgMWdHIFYAQAADQAAAAgAAADMAAAAAQAAAAAAAIDFnRyBAAAAgAYAAAAEAAAAwAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAGgAAADTdNPe" +
    "AAAAAAAAAADNzEw+AAAAAAAAAAAMAAAAAAAAAAAAAAAQAAAAAQAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAFAAAAAABAQEBAQAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALcCAAAjsxP3SEryXzgAAABoAAAACQAAALwCAAC0P1zg" +
    "sN2XyAgAAAAEAQAAAQAAAOoCAABjQtdOUvkhaxAAAAAAAQAABAAAAC4DAADCDAaXVM3PWwcAAAA4AQAABwAAADcDAAAksIqw" +
    "bojSGwgAAACsAQAAAgAAAN0BAAB1RrYoEgAAAAgAAAAAAACA1AEAAAKwjj8SAAAAEAAAAAAAAICkAQAAt90mYw4AAAAAAAAA" +
    "AAAAgPUBAABaMyB0DQAAADQAAAAAAACAzwEAAGZwM3QUAAAAMAAAAAAAAICYAQAAQiksfxIAAAAgAAAAAAAAgHsBAABwubKO" +
    "FQAAABgAAAAAAACAgQEAAE8mBMoKAAAAKAAAAAAAAIB5AQAALebg3BQAAAAsAAAAAAAAgJcBAAD7nT3oDgAAAAAAAAAAAACA" +
    "qgEAAEjoR5oNAAAAAAAAAAAAAIClAQAAOSX0sQoAAAAEAAAAAAAAgJoBAAB9LOnUAAAAAAgAAAAAAACAkwEAAO2EBfsNAAAA" +
    "DAAAAAAAAICoAQAA2hR/AQAAAAABAAAAAAAAgMcBAADeK+YFAAAAAAYAAAAAAACAqgEAAAPbHh8AAAAABQAAAAAAAICLAQAA" +
    "B6fSUAAAAAAEAAAAAAAAgE8BAAA5Da6VAAAAAAAAAAAAAACATQEAAMCGJL8AAAAAAgAAAAAAAIBDAQAA0GqZ+AAAAAADAAAA" +
    "AAAAgHQBAAC1TJ+VBgAAAAQAAAAAAACAWwEAAJOPoNUGAAAAAAAAAAAAAIBhZ2VudHNfYXZhaWxhYmxlAGFzcGlyYXRpb24A" +
    "aWRlYWxfbW9vZABwYXlfdHlwZQBwZXJmb3JtYW5jZV9zdGF0AHB0b19wZXJfZGF5AHRpdGxlAHRpdGxlX2Rlc2NyaXB0aW9u" +
    "AHdvcmtfc2NoZWR1bGUAQ2FyZWVyTGV2ZWwAc2NoZWR1bGVfZW50cmllcwBUdW5hYmxlV2Vla2x5U2NoZWR1bGUAZGF5c19h" +
    "dmFpbGFibGUAZHVyYXRpb24AcmFuZG9tX3N0YXJ0AHN0YXJ0X3RpbWUAVHVuYWJsZVNjaGVkdWxlRW50cnkAMCBTVU5EQVkA" +
    "MSBNT05EQVkAMiBUVUVTREFZADMgV0VETkVTREFZADQgVEhVUlNEQVkANSBGUklEQVkANiBTQVRVUkRBWQBUdW5hYmxlQXZh" +
    "aWxhYmxlRGF5cwBob3VyAG1pbnV0ZQBUdW5hYmxlVGltZU9mRGF5AENvbnN0cnVjdG9yAA==",
  // TraitGameplay.data (1129 bytes)
  trait:
    "REFUQQEBAAAYAAAAAwAAAPABAAABAAAADwAAAAAAAAA9BAAApzcReNgBAAANAAAAkAAAAMwAAAABAAAAAAAAgMWdHIEAAACA" +
    "CAAAAAgAAABAAQAACwAAAAAAAIDFnRyBAAAAgAEAAAABAAAAhAEAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAAIAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAADIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACxAAAAAAAAgAAAAAAAAAAAAAAAgAAAAAD5BjZ4bITwMILYsgAAAAAA" +
    "aAAAAAMAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAVTigwQgAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAQAAAAAAAAA" +
    "AgAAAAAAAABAAAAAAAAAABAAAAAAAAAAgAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOb25lAAAA" +
    "AAAAAAAAAABXAgAAx91fy2avLt6QAAAACAAAABEAAAB5AQAA5VeLBRMAAAAYAAAAAAAAgB8CAAASXfQYFQAAAIgAAAAAAACA" +
    "rgEAAGlpBR4UAAAATAAAAAAAAIDTAQAA030fHhQAAAB8AAAAAAAAgHMBAAAzF8M4DgAAAEQAAAAAAACAfwEAAO0LX2UOAAAA" +
    "UAAAAAAAAIBzAQAAepOqbhMAAABYAAAAAAAAgCMBAACzyEJ4CwAAAEAAAAAAAACAygAAAC65LZMOAAAAEAAAAAAAAIBJAQAA" +
    "8ObHnBQAAAB4AAAAAAAAgGABAAD6MmChCAAAAIAAAAAAAACArgAAAJdINacLAAAAKAAAAAAAAIBkAAAANS/rrw4AAAAAAAAA" +
    "AAAAgPQAAACGCiO4DgAAAHAAAAAAAACAhQAAAPh167gTAAAAMAAAAAAAAIDEAAAAUdKvug4AAABoAAAAAAAAgBkAAABbdDXe" +
    "DgAAAAgAAAAAAACAYWdlcwBiYl9maWx0ZXJfc3R5bGVzAGJiX2ZpbHRlcl90YWdzAGNhc19pZGxlX2FzbV9rZXkAY2FzX2lk" +
    "bGVfYXNtX3N0YXRlAGNhc19zZWxlY3RlZF9pY29uAGNhc190cmFpdF9hc21fcGFyYW0AY29uZmxpY3RpbmdfdHJhaXRzAGRp" +
    "c3BsYXlfbmFtZQBnZW5kZXJzAGljb24Ac3BlY2llcwB0YWdzAHRyYWl0X2Rlc2NyaXB0aW9uAHRyYWl0X29yaWdpbl9kZXNj" +
    "cmlwdGlvbgB0cmFpdF90eXBlAHVpX2NhdGVnb3J5AFRyYWl0AENvbnN0cnVjdG9yAA==",
  // Trait.data (1161 bytes)
  trait_personality:
    "REFUQQEBAAAYAAAAAwAAABACAAABAAAAAAAAAAAAAABdBAAApzcRePgBAAANAAAAkAAAAMwAAAABAAAAAAAAgMWdHIEAAACA" +
    "CAAAAAgAAABAAQAADwAAAAAAAIDFnRyBAAAAgAEAAAABAAAApAEAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAAIAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAADoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADRAAAAAAAAgAAAAAAAAAAAgAAAAAIAAAD5BjZ4bITwMILYsgAAAAAA" +
    "eAAAAAMAAACIAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAACAVTigwQEAAAAAAAAAAgAAAAAAAAAEAAAAAAAAAAgAAAAAAAAA" +
    "EAAAAAAAAAAgAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEFjdGl2ZQAAAAAAAAAAAFcCAADH3V/LyITVU5AAAAAIAAAAEQAAAHkBAADlV4sF" +
    "EwAAABgAAAAAAACAHwIAABJd9BgVAAAAiAAAAAAAAICuAQAAaWkFHhQAAABMAAAAAAAAgNMBAADTfR8eFAAAAHwAAAAAAACA" +
    "cwEAADMXwzgOAAAARAAAAAAAAIB/AQAA7QtfZQ4AAABQAAAAAAAAgHMBAAB6k6puEwAAAFgAAAAAAACAIwEAALPIQngLAAAA" +
    "QAAAAAAAAIDKAAAALrktkw4AAAAQAAAAAAAAgEkBAADw5secFAAAAHgAAAAAAACAYAEAAPoyYKEIAAAAgAAAAAAAAICuAAAA" +
    "l0g1pwsAAAAoAAAAAAAAgGQAAAA1L+uvDgAAAAAAAAAAAACA9AAAAIYKI7gOAAAAcAAAAAAAAICFAAAA+HXruBMAAAAwAAAA" +
    "AAAAgMQAAABR0q+6DgAAAGgAAAAAAACAGQAAAFt0Nd4OAAAACAAAAAAAAIBhZ2VzAGJiX2ZpbHRlcl9zdHlsZXMAYmJfZmls" +
    "dGVyX3RhZ3MAY2FzX2lkbGVfYXNtX2tleQBjYXNfaWRsZV9hc21fc3RhdGUAY2FzX3NlbGVjdGVkX2ljb24AY2FzX3RyYWl0" +
    "X2FzbV9wYXJhbQBjb25mbGljdGluZ190cmFpdHMAZGlzcGxheV9uYW1lAGdlbmRlcnMAaWNvbgBzcGVjaWVzAHRhZ3MAdHJh" +
    "aXRfZGVzY3JpcHRpb24AdHJhaXRfb3JpZ2luX2Rlc2NyaXB0aW9uAHRyYWl0X3R5cGUAdWlfY2F0ZWdvcnkAVHJhaXQAQ29u" +
    "c3RydWN0b3IA",
  // Buff.data (553 bytes)
  buff:
    "REFUQQEBAAAYAAAAAQAAAMAAAAABAAAACgAAAAAAAAD9AQAApzcReKgAAAANAAAAUAAAAEwAAAABAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGxmTPFrn4ir7jBP0AAAAA" +
    "6kZVohYy8zu+4wT9AAAAAAAAAAAAAAAA+QY2eGyE8DCC2LIAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAEgBAACW6Bdg" +
    "VilycVAAAAAIAAAACQAAAMcAAAB44fMaEwAAABAAAAAAAACA6QAAAC+jnBsSAAAAOAAAAAAAAIDQAAAAepOqbhMAAAAoAAAA" +
    "AAAAgKEAAABJiwWRFAAAACAAAAAAAACAngAAAKxVLqIUAAAAJAAAAAAAAICjAAAAc3sltgYAAABAAAAAAAAAgJsAAADW38fA" +
    "FAAAAEQAAAAAAACAlgAAAKfSPNsGAAAASAAAAAAAAIAUAAAAsWlw5hMAAAAAAAAAAAAAgGF1ZGlvX3N0aW5nX29uX2FkZABh" +
    "dWRpb19zdGluZ19vbl9yZW1vdmUAYnVmZl9kZXNjcmlwdGlvbgBidWZmX25hbWUAaWNvbgBtb29kX3R5cGUAbW9vZF93ZWln" +
    "aHQAdGltZW91dF9zdHJpbmcAdWlfc29ydF9vcmRlcgBCdWZmAENvbnN0cnVjdG9yAA==",
  // AspirationTrack.data (817 bytes)
  aspiration:
    "REFUQQEBAAAYAAAAAwAAACABAAACAAAAGQAAAAAAAAAFAwAApzcReAgBAAANAAAAWAAAAEwAAAABAAAAAAAAgMWdHIEEAQAA" +
    "DQAAABAAAACQAAAABAAAAAAAAIDFnRyBAAAAgAEAAAABAAAAtAAAAAEAAAAAAAAAAAAAAAAAAABgAAAABAAAAOqeAgAAAAAA" +
    "dlS4r9qccKIhbAaubGQzNYLYsgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkAAAAAAAAgAAAAAAwnwIAAAAAACefAgAAAAAA" +
    "AAAAAAAAAAABAAAAAAAAAO6eAgAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAMMBAABqzV+YnAFEFVgAAAAgAAAACwAAAMUBAAB8X3dg3PkS0BAAAADkAAAAAgAAAF8BAADu+zQv" +
    "CwAAADwAAAAAAACAagEAABzFGjgSAAAASAAAAAAAAIDxAAAAYV6VThQAAAAQAAAAAAAAgA4BAACHE/ROAAAAADgAAAAAAACA" +
    "5wAAAHqTqm4TAAAAGAAAAAAAAIAoAQAAKJikbxIAAABQAAAAAAAAgMQAAAAKbE9wEwAAACgAAAAAAACA4gAAABdcRHEOAAAA" +
    "QAAAAAAAAICKAAAANXswihQAAAAUAAAAAAAAgFAAAABc6vCLDgAAAAAAAAAAAACASAAAAOFfhqESAAAACAAAAAAAAIDLAAAA" +
    "3GPtKBIAAAAIAAAAAAAAgLMAAACCLoRGCAAAAAAAAAAAAACAYXNwaXJhdGlvbnMAY2F0ZWdvcnkAZGVzY3JpcHRpb25fdGV4" +
    "dABkaXNwbGF5X3RleHQAaWNvbgBpY29uX2hpZ2hfcmVzAGlzX2hpZGRlbl91bmxvY2thYmxlAG1vb2RfYXNtX3BhcmFtAG92" +
    "ZXJyaWRlX3RyYWl0cwBwcmltYXJ5X3RyYWl0AHJld2FyZABBc3BpcmF0aW9uVHJhY2sAa2V5AHZhbHVlAEFzcGlyYXRpb25z" +
    "TWFwcGluZ1R1cGxlAENvbnN0cnVjdG9yAA==",
  // Milestone.data (625 bytes)
  milestone:
    "REFUQQEBAAAYAAAAAgAAAPAAAAABAAAAPwAAAAAAAABFAgAApzcReNgAAAANAAAAQAAAAEwAAAABAAAAAAAAgMWdHIEAAACA" +
    "CAAAAAgAAABwAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAACAAAAAUAAAAAAAAA" +
    "UEhtuOn8AfeC2LIAAAAAAAAAAIAqsimSTHypfegDAAA2aXU2Nml1NgAAAAAAAAAAqAEAAAAAAAACAAAAAAAAAAQAAAAAAAAA" +
    "CAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAE4BAADTyYNjlh/th0AAAAAIAAAACQAAABYBAAAAue4n" +
    "FAAAADgAAAAAAACAyAAAAPQ7iy8UAAAAKAAAAAAAAICaAAAAepOqbhMAAAAQAAAAAAAAgIsAAACNGOaFFQAAACAAAAAAAACA" +
    "aQAAAOFfhqEHAAAACAAAAAAAAIBQAAAANS/rrw4AAAAAAAAAAAAAgIUAAABO+0rSFAAAADQAAAAAAACAYwAAALSf9tgUAAAA" +
    "MAAAAAAAAIBBAAAAp9I82wYAAAAsAAAAAAAAgGFnZXMAY2F0ZWdvcnkAaWNvbgBpc19wcmltYXJ5X21pbGVzdG9uZQBuYW1l" +
    "AHVpX3NvcnRfb3JkZXIAdW5sb2NrZWRfdGV4dAB1bmxvY2tlZF90ZXh0X25vX2NvbnRleHQAdW5sb2NrZWRfdGV4dF90YXJn" +
    "ZXRfc2ltX2hlYWRlcgBEZXZlbG9wbWVudGFsTWlsZXN0b25lAENvbnN0cnVjdG9yAA==",
  // Objective.data (227 bytes)
  objective:
    "REFUQQEBAAAYAAAAAQAAAEAAAAABAAAAAAAAAAAAAAC3AAAApzcReCgAAAANAAAADAAAAAwAAAABAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAB9AAAAPkVpAKXrz9UMAAAACAAAAAMAAABJAAAABb/ffgYAAAAEAAAAAAAAgCgAAAA1ezCKFAAAAAAAAAAAAACA" +
    "NQAAACp4SMwUAAAACAAAAAAAAIBkaXNwbGF5X3RleHQAc2F0aXNmYWN0aW9uX3BvaW50cwB0b29sdGlwAE9iamVjdGl2ZQBD" +
    "b25zdHJ1Y3RvcgA=",
};
/* eslint-enable */

function decode(b64: string): Uint8Array {
  if (typeof atob === "function") {
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  return new Uint8Array(Buffer.from(b64, "base64"));
}

/** Builder kind -> template name in the built-in set. */
const KIND_TEMPLATE: Partial<Record<BuilderKind, string>> = {
  career: "career",
  career_level: "career_level",
  trait: "trait",
  buff: "buff",
  aspiration: "aspiration",
  milestone: "milestone",
};

const cache = new Map<string, Uint8Array>();

export function simDataTemplate(name: string): Uint8Array | undefined {
  const b64 = TEMPLATES_B64[name];
  if (!b64) return undefined;
  const hit = cache.get(name);
  if (hit) return hit;
  const bytes = decode(b64);
  cache.set(name, bytes);
  return bytes;
}

/** True when this build can generate a SimData companion for the kind. */
export function hasSimDataTemplate(kind: BuilderKind) {
  return Boolean(KIND_TEMPLATE[kind]);
}

export function templateForKind(kind: BuilderKind): { name: string; bytes: Uint8Array } | undefined {
  const name = KIND_TEMPLATE[kind];
  if (!name) return undefined;
  const bytes = simDataTemplate(name);
  return bytes ? { name, bytes: new Uint8Array(bytes) } : undefined;
}

export const TEMPLATE_NAMES = Object.keys(TEMPLATES_B64);
